# Generated by Django 5.2.4 on 2025-09-10 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
